### PR TITLE
Added await for router

### PR DESCRIPTION
**Pull request by ahaneef29**
This PR will add missing await keyword and added set timeout for initial PHP path validate after app started.

### CODE REVIEW

**Comment by saeedvaziry** [comment]
Why timeout?

**Comment by ahaneef29** [comment]
Dev version is picking PHP path after the app initialized and started, but in production build it required some timeout to initialize the PHP path.

**Comment by saeedvaziry** [comment]
I don't think we need a timeout here.

Instead we can just switch these two lines together

https://github.com/tweakphp/tweakphp/blob/main/src/renderer/App.vue#L61-L62

**Comment by ahaneef29** [comment]
I will revert the changes and I will update PR only to add await keyword

**Comment by saeedvaziry** [comment]
@ahaneef29 are you also swapping those 2 lines I mentioned?

**Comment by ahaneef29** [comment]
No, I updated this PR for to fix only `await` keyword.

**Pull request merged**
