### PR TITLE
Improved php version detect and fix 

### PR DESCRIPTION
**Pull request by Kamleshpaul**
- This PR include fixes :  https://github.com/tweakphp/tweakphp/issues/16

- Added `Fix php path` button 

Screenshot 2024-11-12 at 3 58 23 PM

### CODE REVIEW

**Comment by saeedvaziry** [comment]
I am doing some refactoring which is required in order to make the app release ready. keeping this PR on hold until the refactoring is ready.

**Comment by saeedvaziry** [comment]
Closing this one due to a lot of conflicts that I made with the refactoring 😂 also the solution doesn't work after building the app. need to figure this out.

**Comment by Kamleshpaul** [comment]
sure I will check

**Comment by Kamleshpaul** [comment]
i think we don't need this button for now as it should automatically detect ?

by https://github.com/tweakphp/tweakphp/blob/7d09a1978604a06660787139801a72eeeff7ee54/src/renderer/App.vue#L49

or do we need ?

**Pull request closed without merging**
