### PR TITLE
Linux build

### LINKED ISSUE #36: Linux Build
Build for linux

### PR DESCRIPTION
**Pull request by saeedvaziry**
closes #36

### CODE REVIEW

**Comment by saeedvaziry** [comment]
@luanfreitasdev looks like having trouble with auto update on linux. considering you've done this 😅, any tips you can share?

**Comment by luanfreitasdev** [comment]
What problem did you have?

**Comment by saeedvaziry** [comment]
Ah all good. I was missing APPIMAGE env to get it work

**Comment by luanfreitasdev** [comment]
I never needed to set APPIMAGE in the env 🧐

**Pull request merged**
