### PR TITLE
[Enhancement] Docker Linux 🐧

### PR DESCRIPTION
**Pull request by luanfreitasdev**
### BLOCKED BY [LINUX BRANCH](https://github.com/tweakphp/tweakphp/tree/linux)

https://github.com/tweakphp/tweakphp/issues/36

### To run docker on Linux you need to do it with sudo. Two different approaches to this:

1. Whenever you connect to a container or user, type a password (this is annoying, but it's normal in some apps)
2. Tell sudo that `/usr/bin/docker` doesn't need a password (my favorite)

---

To do this, the user must first execute some commands:

1. `whoami` - get username
2. `sudo visudo` 

Add in the last line:

`your_user_name ALL=(ALL) NOPASSWD: /usr/bin/docker` - (replace your_user_name to name generated in whoami)

### CODE REVIEW

**Comment by saeedvaziry** [comment]
Can't we do the solution 2 using solution 1?

**Comment by luanfreitasdev** [comment]
The first solution would open a modal every time the user adds a container to a project. The second solves the problem

**Comment by saeedvaziry** [comment]
I am not really sure, kinda modifying user's system settings with the solution 2. also the first solution is not really convenient

**Comment by luanfreitasdev** [comment]
any suggestions? I think docker doesn't work on Linux without sudo

**Comment by saeedvaziry** [comment]
I think lets start with solution 1 and see how is the feedback. we're still in beta so there is plenty of room to improve.

**Comment by saeedvaziry** [comment]
btw, the linux branch is merged now.

**Comment by luanfreitasdev** [comment]
After PR #44 and with these steps described in the docker doc, I tested it on Pop OS and it worked

https://docs.docker.com/engine/install/linux-postinstall/

image

**Comment by luanfreitasdev** [comment]
image

**Comment by luanfreitasdev** [comment]
@saeedvaziry . Some observations outside the scope.

On PopOS, the context menu does not appear correctly
The title is tweakphp instead of TweekPHP

**Comment by saeedvaziry** [comment]
Can you drop a screenshot please? Ubuntu was fine as I tested. Not sure about the title tho

**Comment by luanfreitasdev** [comment]
> image

@saeedvaziry

**Comment by saeedvaziry** [comment]
The menu looks fine. I made some changes to show it a bit different on other OSs than mac

But the title yeah should be TweakPHP and this one loads from the package.json I guess. Should be easy to fix by setting it on the main window in main.ts

**Comment by luanfreitasdev** [comment]
Only title and icon confimed: https://github.com/tweakphp/tweakphp/issues/49

**Pull request merged**
