### PR TITLE
feat :  Improve PHP path retrieval with multiple methods

### PR DESCRIPTION
**Pull request by Kamleshpaul**
This might fix https://github.com/tweakphp/tweakphp/issues/16

it works in my system need to test more

### CODE REVIEW

**Comment by saeedvaziry** [comment]
I've been asking myself does it really make sense to run all those commands to just figure out the PHP path?

If we add linux and windows we might need to add more commands there.

Also I don't want to crash the app if there is no PHP. (throw Error will crash the app)

**Comment by Kamleshpaul** [comment]
Yeah i agree.
What needs to be done ? then i can take a look in to this

**Comment by saeedvaziry** [comment]
So don't you think it would be more convenient at this stage to let the user enter the PHP path?

The idea is to reach to an stable release for now

**Comment by Kamleshpaul** [comment]
If goal is to stable release then it is fine user can set php path

**Comment by saeedvaziry** [comment]
Closing this one for now. And thanks for the effort @Kamleshpaul

**Pull request closed without merging**
