### PR TITLE
Docker code execution

### PR DESCRIPTION
**Pull request by luanfreitasdev**
### Add Docker code execution

https://github.com/tweakphp/tweakphp/issues/9

https://github.com/user-attachments/assets/4a6351e9-b940-4481-8511-115e0962a897

### CODE REVIEW

**Comment by saeedvaziry** [comment]
Looking good. Does the LSP still works? (I guess it shouldn't be affected cause the path is the same)

**Comment by luanfreitasdev** [comment]
> Looking good. Does the LSP still work? (I guess it shouldn't be affected cause the path is the same)

It works, but if there is no PHP on the machine and the user wants to use only Docker, it will not work. We would have to copy phpactor inside the container in this case. What do you think?

**Comment by saeedvaziry** [comment]
Not sure how it can work if we copy the phpactor, cause we run it in the machine itself and it opens a port. in this case we might need to open websocket port in the container and expose it which would be too complex.

Lets leave it like that for now.

**Comment by luanfreitasdev** [comment]
@saeedvaziry . Ready for review, feel free to change anything. Thanks for the great app 🤟

**Comment by saeedvaziry** [comment]
CleanShot 2024-12-26 at 14 12 08@2x
really like this button 😍

**Comment by saeedvaziry** [comment]
> feel free to change anything

I will make a few adjustments like the following:

If I open project X and go to docker and select project Y's container it will connect it in the same tab, so the auto completion will work on the project X but the code on project Y. also if I turn on and off the docker the same code might not get executed and fail due to different project

I still don't know what is the best approach TBH. but lemme see what is more convenient.

Anyway, Thanks for the PR. everything works perfect!

**Comment by luanfreitasdev** [comment]
> > feel free to change anything
> 
> I will make a few adjustments like the following if you don't mind:
> 
> If I open project X and go to docker and select project Y's container it will connect it in the same tab, so the auto completion will work on the project X but the code on project Y. also if I turn on and off the docker the same code might not get executed and fail due to different project
> 
> I still don't know what is the best approach TBH. but lemme see what is more convenient.
> 
> Anyway, Thanks for the PR. everything works perfect!

It seems good

**Comment by luanfreitasdev** [comment]
[8a86eb2](https://github.com/tweakphp/tweakphp/pull/31/commits/8a86eb21b61bc75f1c4595d064bcb5cc99fdb211)

This commit was necessary to make the app work in production. For now, it only works with macOS.

**Comment by luanfreitasdev** [comment]
We still need a way to ensure that the client is always up to date in the container. @saeedvaziry Do you have any ideas?

**Comment by saeedvaziry** [comment]
> We still need a way to ensure that the client is always up to date in the container

not sure I get your point here

**Comment by luanfreitasdev** [comment]
When we enable docker in a project, the client-x.x.phar file is copied only once, let's assume there are new clients on github (https://github.com/tweakphp/client) or the app has been updated, so the container will not work correctly with them.

**Comment by saeedvaziry** [comment]
hmm, if user closes the tab and reopens and reconnects docker, would it handle it?

**Comment by luanfreitasdev** [comment]
I think we can copy phar on the first run too

https://github.com/tweakphp/tweakphp/pull/31/commits/e16a5487b3d54961fcf44ea6fa3b76410c8b1648#diff-bce28e1da82f78a29346d738fa9d78edce50c67a571384c4cb62b0096ec707c1R93

**Comment by saeedvaziry** [comment]
Is this happening to you too?
CleanShot 2024-12-26 at 18 14 20@2x

**Comment by luanfreitasdev** [comment]
Try connecting docker again to update the "php_version" in the tab

**Comment by luanfreitasdev** [comment]
It didn't happen to me anymore, maybe it's the "[never](https://github.com/tweakphp/tweakphp/pull/31/commits/d0627b4eab0e7d8a077902b2b1dfe9e370ddcec0#diff-bce28e1da82f78a29346d738fa9d78edce50c67a571384c4cb62b0096ec707c1L82)" type I put before

**Comment by saeedvaziry** [comment]
Alright! Merging it. Great work @luanfreitasdev

**Comment by saeedvaziry** [comment]
and forgot to squash 😅

**Pull request merged**
