### PR TITLE
DockerView improves

### PR DESCRIPTION
**Pull request by luanfreitasdev**
* Improve execAsync response
* Improve typescript
* Remove unused function (docker-which-php)
* Improve status logic

### CODE REVIEW

**Comment by saeedvaziry** [comment]
PR looks good.

WDYT we update all ipc channel names to one naming convention? Looks like its a bit mixed now.

**Comment by luanfreitasdev** [comment]
Yes, I thought about leaving "action-type", where the type can be `response` or `error`. Where is it confusing?

**Comment by saeedvaziry** [comment]
Its not confusing. just convention. 

CleanShot 2024-12-29 at 20 10 09@2x


Like some with dashes and some with dots :)

Tho, something to think about it later.

**Comment by luanfreitasdev** [comment]
Well observed. I think with a point it becomes clearer

**Pull request merged**
